export const data = [
    
        {
          "Ticker": "BBUS AU",
          "Name": "BETASHARES US EQ STR BEAR-CH",
          "Total Assets": 250.8201,
          "Price": 7.81,
          "1YR TR%": -17.26695,
          "3YR TR%": -26.47347,
          "Tracking Error": "45.538",
          "Expense Ratio": "1.38",
          "Description": "BetaShares U.S. Equities Strong Bear Hedge Fund - Currency Hedged is an exchange-traded fund incorporated in Australia. The Fund objective seeks to generate returns that are negatively correlated to the returns of the U.S. share market (as measured by the S&P 500  index), hedged to Australian dollars."
        },
        {
          "Ticker": "MNRS AU",
          "Name": "BETA GLB GOLD MINERS-CURR HG",
          "Total Assets": 55.40017,
          "Price": 5.18,
          "1YR TR%": 7.60931,
          "3YR TR%": -11.84173,
          "Tracking Error": "19.2624",
          "Expense Ratio": "0.57",
          "Description": "BetaShares Global Gold Miners ETF - Currency Hedged is an exchange-traded fund incorporated in Australia. The investment objective of the fund is to provide an investment return that aims to track the performance of the Nasdaq Global exAustralia Gold Miners Hedged AUD Index (the \"Index\"), before taking into account fees and expenses."
        },
        {
          "Ticker": "BEAR AU",
          "Name": "BETASHARES AUS EQ BEAR HF",
          "Total Assets": 50.71682945,
          "Price": 8.36,
          "1YR TR%": -6.067416,
          "3YR TR%": -10.08633,
          "Tracking Error": "24.9501",
          "Expense Ratio": "1.38",
          "Description": "BetaShares Australian Equities Bear Hedge Fund is an exchange-traded fund incorporated in Australia. The Fund's objective is to help investors profit from, or protect against, a declining Australian share market by seeking to generate returns that are negatively correlated to the returns of the Australian share market (as measured by the S&P/ASX 200 index)."
        },
        {
          "Ticker": "CURE AU",
          "Name": "GLOBAL X S&P BIOTECH ETF",
          "Total Assets": 37.57426,
          "Price": 41.82,
          "1YR TR%": -5.789592,
          "3YR TR%": -8.570654,
          "Tracking Error": "19.9052",
          "Expense Ratio": "0.45",
          "Description": "Global X S&P Biotech ETF is an exchange traded fund incorporated in Australia. The fund aims to provide investors with a return that (before fees and expenses) tracks the performance of the S&P Biotechnology Select Industry Index."
        },
        {
          "Ticker": "GDX AU",
          "Name": "VANECK GOLD MINERS ETF",
          "Total Assets": 426.6519,
          "Price": 44.49,
          "1YR TR%": 17.55352,
          "3YR TR%": -8.548009,
          "Tracking Error": "17.3281",
          "Expense Ratio": "0.53",
          "Description": "VanEck Vectors Gold Miners ETF is an exchange-traded fund incorporated in Australia. The ETF aims to provide investment returns before fees and other costs which track the performance of the NYSE Arca Gold Miners Index (AUD). Its largest allocation is in North American companies, principally those domiciled in Canada. The ETF weights the holdings using a market capitalisation methodology."
        },
        {
          "Ticker": "CNEW AU",
          "Name": "VANECK CHINA NEW ECONOMY ETF",
          "Total Assets": 120.7713,
          "Price": 7.02,
          "1YR TR%": -6.204543,
          "3YR TR%": -8.492974,
          "Tracking Error": "8.01566",
          "Expense Ratio": "0.95",
          "Description": "VanEck Vectors China New Economy ETF is an exchange-traded fund incorporated in Australia. The ETF seeks to provide investors with access to a portfolio of the most fundamentally sound companies with the best growth prospects in the consumer discretionary, consumer staples, healthcare, and technology sectors that are domiciled and listed in China."
        },
        {
          "Ticker": "IZZ AU",
          "Name": "ISHARES CHINA LARGE-CAP/AUD",
          "Total Assets": 322.9343,
          "Price": 43.7,
          "1YR TR%": 7.543708,
          "3YR TR%": -8.088144,
          "Tracking Error": "9.30715",
          "Expense Ratio": "0.74",
          "Description": "iShares China Large-Cap ETF is an exchange-traded fund incorporated in Australia .The ETF tracks the FTSE China 50 Index, investing in large cap stocks. Its investments are focused in the financial, oil and gas, technology and communications sectors. The ETF uses a representative sampling indexing strategy ,investing at least 90% of its assets in the securities of the underlying index."
        },
        {
          "Ticker": "ASIA AU",
          "Name": "BETASHARES ASIA TECH TIGERS",
          "Total Assets": 488.291,
          "Price": 7.7,
          "1YR TR%": 14.47108,
          "3YR TR%": -5.168025,
          "Tracking Error": "10.7323",
          "Expense Ratio": "0.67",
          "Description": "BetaShares Asia Technology Tigers ETF is a exchanged traded fund incorporated in Australia. The Fund aims to provide an investment return that aims to track the performance of the Solactive Asia ex-Japan Technology & Internet Tigers Index (the \"Index\"), before taking into account fees and expenses."
        },
        {
          "Ticker": "CETF AU",
          "Name": "VANECK FTSE CHINA A50 ETF",
          "Total Assets": 20.15743,
          "Price": 55.1,
          "1YR TR%": 0.9817619,
          "3YR TR%": -1.560851,
          "Tracking Error": "7.17187",
          "Expense Ratio": "0.6",
          "Description": "VanEck Vectors FTSE China A50 ETF is an exchange traded fund incorporated in Australia. The ETF aims to provide investment returns before fees and other costs which track the performance of the FTSE China A50 Net Tax AUD Index. The ETF invests in 50 of the largest companies by full market capitalisation, in the mainland Chinese market."
        },
        {
          "Ticker": "IAA AU",
          "Name": "ISHARES ASIA 50/AUS",
          "Total Assets": 731.3839,
          "Price": 91.33,
          "1YR TR%": 10.72113,
          "3YR TR%": -1.162564,
          "Tracking Error": "9.23212",
          "Expense Ratio": "0.5",
          "Description": "iShares Asia 50 ETF/Australia is an exchange-traded fund incorporated in Australia. The Fund invests to the underlying iShares Asia 50 ETF that is incorporated in US and seeks investment results that correspond to the S&P Asia 50 Index."
        },
        {
          "Ticker": "EMMG AU",
          "Name": "BETAS MRTN CURIE EMEG MKT FD",
          "Total Assets": 123.3389614,
          "Price": 5.92,
          "1YR TR%": 10.76725,
          "3YR TR%": 0.193469,
          "Tracking Error": "7.11555",
          "Expense Ratio": "1",
          "Description": "BetaShares  Martin Currie  Emerging Markets Fund (managed fund) is an exchange traded fund incorporated in Australia. The Fund aims to generate after fee returns in excess of the MSCI Emerging Markets Index expressed in Australian dollars over rolling five-year periods."
        },
        {
          "Ticker": "MHG AU",
          "Name": "MAGELLAN GLB EQUITIES-CURR H",
          "Total Assets": 115.7801,
          "Price": 3.22,
          "1YR TR%": 3.080988,
          "3YR TR%": 0.9505505,
          "Tracking Error": "10.2863",
          "Expense Ratio": "1.35",
          "Description": "Magellan Global Equity Fund - Currency Hedged is an exchange-traded fund incorporated in Australia. The Fund primarily invests in securities of companies listed on stock exchanges around the world. The primary objectives of the Fund are to achieve attractive risk adjusted returns over the medium to long term while reducing the risk of permanent capital loss."
        },
        {
          "Ticker": "ZYAU AU",
          "Name": "GLOBAL X S&P/ASX 200 HI DIV",
          "Total Assets": 66.08095,
          "Price": 8.36,
          "1YR TR%": 2.289654,
          "3YR TR%": 1.092843,
          "Tracking Error": "6.35705",
          "Expense Ratio": "0.24",
          "Description": "Global X S&P/ASX 200 High Dividend ETF is an exchange-traded fund incorporated in  Australia. The Fund aims to provide investors with a return that (before fee sand expenses) tracks the performance of the S&P/ASX 200 High Dividend Index."
        },
        {
          "Ticker": "IEM AU",
          "Name": "ISHARES MSCI EMERGING MK",
          "Total Assets": 888.487517,
          "Price": 61.01,
          "1YR TR%": 9.793264,
          "3YR TR%": 1.622077,
          "Tracking Error": "7.88556",
          "Expense Ratio": "0.67",
          "Description": "iShares MSCI Emerging Markets ETF/AU is an exchange-traded fund incorporated in Australia. The ETF tracks the performance of the MSCI TR Emerging Markets Index. The ETF holds emerging market stocks that can predominantly be classified as large and mid-cap. It weights the holdings using a market capitalization methodology and rebalances quarterly."
        },
        {
          "Ticker": "REIT AU",
          "Name": "VANECK FTSE INTERNATIONAL PR",
          "Total Assets": 242.9477,
          "Price": 15.41,
          "1YR TR%": -11.83421,
          "3YR TR%": 1.811197,
          "Tracking Error": "11.7457",
          "Expense Ratio": "0.2",
          "Description": "VanEck Vectors FTSE International Property (Hedged) ETF is an exchange-traded fund incorporated in Australia.  The ETF aims to provide investment returns before fees and other costs which track the performance of its Reference Index in Australian dollars."
        },
        {
          "Ticker": "VAE AU",
          "Name": "VANGUARD FTSE ASIA EX-JAP SH",
          "Total Assets": 360.3433,
          "Price": 69.82,
          "1YR TR%": 9.394141,
          "3YR TR%": 1.923495,
          "Tracking Error": "6.10941",
          "Expense Ratio": "0.4",
          "Description": "Vanguard FTSE Asia ex-Japan Shares Index ETF is an exchange-traded find incorporated in Australia. The fund seeks to track the return of the FTSE Asia Pacific ex Japan, Australia and New Zealand (with net dividends reinvested), in Australian dollars Index, before taking into account fees, expenses and tax."
        },
        {
          "Ticker": "PAXX AU",
          "Name": "PLATINUM ASIA FUND ETF",
          "Total Assets": 106.5166206,
          "Price": 4.38,
          "1YR TR%": 13.68488,
          "3YR TR%": 2.38747,
          "Tracking Error": "#N/A N/A",
          "Expense Ratio": "1.1",
          "Description": "Platinum Asia Fund ETF is an exchange-traded fund incorporated in Australia. The PAXX will primarily invest in units of the Platinum Asia Fund (\"PAF\" or \"Underlying Fund\") and some cash."
        },
        {
          "Ticker": "MICH AU",
          "Name": "MAGELLAN INFRA FUND-CURR HGD",
          "Total Assets": 720.1338,
          "Price": 2.69,
          "1YR TR%": -8.943359,
          "3YR TR%": 2.527883,
          "Tracking Error": "10.0456",
          "Expense Ratio": "1.05",
          "Description": "Magellan Infrastructure Fund - Currency Hedged is an exchange-traded fund incorporated in Australia. The fund is a long-only global infrastructure fund. The primary objectives are to achieve attractive risk-adjusted returns over the medium to long-term while reducing the risk of permanent capital loss."
        },
        {
          "Ticker": "WEMG AU",
          "Name": "SPDR S&P EMERG CARBON CONT",
          "Total Assets": 19.46,
          "Price": 22.05,
          "1YR TR%": 10.47587,
          "3YR TR%": 3.056857,
          "Tracking Error": "7.87033",
          "Expense Ratio": "0.65",
          "Description": "The SPDR S&P Emerging Market Carbon Control is an exchange traded fund incorporated in Australia. The fund seeks to closely track, before fees and expenses, the returns of the S&P Emerging LargeMidCap Carbon Control Index (AUD)."
        },
        {
          "Ticker": "VMIN AU",
          "Name": "VANGUARD GLB MIN VOL ACT ETF",
          "Total Assets": 16.1859,
          "Price": 53.28,
          "1YR TR%": 1.932271,
          "3YR TR%": 3.090845,
          "Tracking Error": "10.8731",
          "Expense Ratio": "0.28",
          "Description": "Vanguard Global Minimum Volatility Active ETF is an exchange traded fund incorporated in Australia. The Fund seeks to provide long-term capital appreciation with volatility lower than the FTSE Global All-Cap Index (AUD hedged), before taking into account fees, expenses and tax."
        },
        {
          "Ticker": "VGE AU",
          "Name": "VANGUARD FTSE EMERG MKTS ETF",
          "Total Assets": 742.8713,
          "Price": 69.79,
          "1YR TR%": 9.829636,
          "3YR TR%": 3.473713,
          "Tracking Error": "6.44286",
          "Expense Ratio": "0.48",
          "Description": "Vanguard FTSE Emerging Markets ETF is an exchange-traded fund incorporated in Australia. The Fund seeks to track the performance of the FTSE Emerging Markets Index. The Fund invests in the Vanguard FTSE Emerging Markets ETF listed on NYSE Arca (NYSE Code: VWO). The US ETF seeks to track the FTSE Emerging Index in USD."
        },
        {
          "Ticker": "IKO AU",
          "Name": "ISHARES MSCI SOUTH KOREA ETF",
          "Total Assets": 150.0288,
          "Price": 99.53,
          "1YR TR%": 14.1671,
          "3YR TR%": 3.865422,
          "Tracking Error": "8.7971",
          "Expense Ratio": "0.59",
          "Description": "iShares MSCI South Korea ETF/AU is an exchange traded fund incorporated in Australia.The ETF tracks the performance of the MSCI Korea 25-50 USD Index. The fund holdscompanies of all market caps which are primarily traded on the Korean exchange. The ETF's holdings are primarily focused in the consumer discretionary , financial and information technology sectors."
        },
        {
          "Ticker": "RBTZ AU",
          "Name": "BETASHARES GB ROBOT N AI",
          "Total Assets": 203.7765,
          "Price": 12.39,
          "1YR TR%": 27.26811,
          "3YR TR%": 4.015802,
          "Tracking Error": "8.37419",
          "Expense Ratio": "0.57",
          "Description": "BetaShares Global Robotics And Artificial Intelligence ETF is a exchanged traded fund incorporated in Australia. The Fund aims to provide an investment return that aims to track the performance of the Index Global Robotics & Artificial Intelligence Thematic Index (the \"Index\"), before taking into account fees and expenses."
        },
        {
          "Ticker": "ISO AU",
          "Name": "ISHARES S&P/ASX SMALL ORDINA",
          "Total Assets": 123.3819,
          "Price": 4.37,
          "1YR TR%": -3.13837,
          "3YR TR%": 4.021017,
          "Tracking Error": "2.40152",
          "Expense Ratio": "0.55",
          "Description": "iShares S&P/ASX Small Ordinaries ETF is an exchange-traded fund incorporated in Australia. The Fund seeks to track the performance of the S&P/ASX Small Ordinaries Index, an established index which represents small-cap companies in Australia."
        },
        {
          "Ticker": "ATEC AU",
          "Name": "BETASHARES S&P/ASX AU TECH",
          "Total Assets": 197.7573,
          "Price": 19.81,
          "1YR TR%": 14.68642,
          "3YR TR%": 4.096791,
          "Tracking Error": "1.66017",
          "Expense Ratio": "0.48",
          "Description": "BetaShares S&P/ASX Australian Technology ETF is an exchange traded fund incorporated in Australia. The Fund aims to provide an investment return that aims to track the performance of the S&P/ASX Technology Index, before taking into account fees an expenses."
        },
        {
          "Ticker": "SSO AU",
          "Name": "SPDR S&P/ASX SMALL ORD FUND",
          "Total Assets": 26.81,
          "Price": 13.09,
          "1YR TR%": -3.030928,
          "3YR TR%": 4.211544,
          "Tracking Error": "2.15708",
          "Expense Ratio": "0.5",
          "Description": "SPDR S&P/ASX Small Ordinaries Fund is an exchange traded fund. The ETF provides investors an interest in a diversified portfolio of Australian listed securities, reflecting or closely tracking (before fees and expenses) the S&P/ASX Small Ordinaries Index comprising shares in companies in the S&P/ASX 300 Index, but excluding those in the S&P/ASX 100 Index."
        },
        {
          "Ticker": "IFRA AU",
          "Name": "VANECK FTSE GLOBAL INFRASTRU",
          "Total Assets": 805.6942,
          "Price": 19.77,
          "1YR TR%": -9.774349,
          "3YR TR%": 4.261049,
          "Tracking Error": "9.00174",
          "Expense Ratio": "0.2",
          "Description": "VanEck Vectors FTSE Global Infrastructure (Hedged) ETF is an exchange traded fund incorporated in Australia. The fund aims to provide investment returns that closely track the returns of the FTSE Developed Core Infrastructure 50/50 Hedged into AUD Index."
        },
        {
          "Ticker": "MVS AU",
          "Name": "VANECK SMALL COMPANIES MASTE",
          "Total Assets": 49.59487,
          "Price": 18.43,
          "1YR TR%": -1.503867,
          "3YR TR%": 4.34502,
          "Tracking Error": "4.52672",
          "Expense Ratio": "0.49",
          "Description": "VanEck Vectors Small Companies Masters ETF is an exchange traded fund incorporated in Australia. The Fund aims to provide investment returns that closely track the returns of the MVIS Australia Small-Cap Dividend Payers Index."
        },
        {
          "Ticker": "MOGL AU",
          "Name": "MONTAKA GLOBAL LONG ONLY EQT",
          "Total Assets": 66.09235,
          "Price": 3.3,
          "1YR TR%": 17.6593,
          "3YR TR%": 4.515426,
          "Tracking Error": "14.4796",
          "Expense Ratio": "1.32",
          "Description": "Montaka Global Long Only Equities Fund (Managed Fund) is an exchange traded fund incorporated in Australia. The Fund aims to provide investors with long term capital growth as well as income distributions. The Fund aims to outperform the MSCI World Net Total Return Index, in Australian Dollars over a rolling 5-year period, net of fees."
        },
        {
          "Ticker": "AUST AU",
          "Name": "BETASHARES MANAGED RISK AUST",
          "Total Assets": 27.86453,
          "Price": 15.98,
          "1YR TR%": 2.655238,
          "3YR TR%": 4.559013,
          "Tracking Error": "4.86258",
          "Expense Ratio": "0.1",
          "Description": "BetaShares Managed Risk Australian Share Fund is an exchange traded fund incorporated in Australia. The Fund aims to provide exposure to a broadly diversified portfolio of Australian shares, generally consisting of 200 of the largest equity securities on the ASX. It also aims to reduce the volatility of the Fund's equity investment returns and cushion downside risk."
        },
        {
          "Ticker": "HVST AU",
          "Name": "BETASHARES AU DVD HARVESTER",
          "Total Assets": 183.7971,
          "Price": 12.4,
          "1YR TR%": 7.064245,
          "3YR TR%": 4.648823,
          "Tracking Error": "#N/A N/A",
          "Expense Ratio": "0.72",
          "Description": "BetaShares Australian Dividend Harvester Fund is an exchange-traded fund incorporated in Australia. The fund aims to provide regular income, comprising dividends and franking credits from Australian shares, that is at least double the income yield of the broad Australian share market (as measured by the S&P/ASX 200 Index) on an annual basis."
        },
        {
          "Ticker": "FEMX AU",
          "Name": "FIDELITY GLB EMEG MKT EQMF",
          "Total Assets": 217.5743,
          "Price": 6.13,
          "1YR TR%": 11.21353,
          "3YR TR%": 4.837072,
          "Tracking Error": "7.40548",
          "Expense Ratio": "0.99",
          "Description": "Fidelity Global Emerging Markets Fund (Managed Fund) is an exchange quoted managed fund incorporated in Australia. The Fund seeks to achieve returns in excess of the MSCI Emerging Markets Index NR over the suggested minimum period of 7 years plus. The Fund invests in a selection of securities exposed to emerging markets."
        },
        {
          "Ticker": "FAIR AU",
          "Name": "BETASHARES AU SUST-LEAD ETF",
          "Total Assets": 1278.92,
          "Price": 18.45,
          "1YR TR%": 6.122192,
          "3YR TR%": 5.771626,
          "Tracking Error": "1.50985",
          "Expense Ratio": "0.49",
          "Description": "Betashares Australian Sustainability Leaders ETF is an exchange traded fund incorporated in Australia. The fund provides an investment return that aims to track the performance of the Nasdaq Future Australian Sustainability Leaders Index (the \"Index\") which involves companies that engage in sustainable businesss activities and avoids those who conduct irresponsible actions."
        },
        {
          "Ticker": "SMLL AU",
          "Name": "BETASHARES AUS SMALL COMP SE",
          "Total Assets": 72.64725,
          "Price": 3.38,
          "1YR TR%": 0.4394872,
          "3YR TR%": 5.968397,
          "Tracking Error": "6.61718",
          "Expense Ratio": "0.39",
          "Description": "BetaShares Australian Small Companies Fund is an exchange-traded fund incorporated in Australia. The Fund aims to provide investors with capital growth and income from a portfolio of small company shares listed on the ASX that has the potential to outperform (after fees and expenses) the Fund's benchmark over the medium to long term."
        },
        {
          "Ticker": "WCMQ AU",
          "Name": "WCM QUALITY GLOBAL GROWTH FD",
          "Total Assets": 279.934,
          "Price": 7.53,
          "1YR TR%": 13.40362,
          "3YR TR%": 6.019877,
          "Tracking Error": "9.43688",
          "Expense Ratio": "1.35",
          "Description": "WCM Quality Global Growth Fund (Quoted Managed Fund) is an exchange traded fund incorporated in Australia. The Fund aims to exceed its benchmark, the MSCI All Country World Index ex-Australia (with gross dividends reinvested reported in AUD unhedged). The Fund will invest in a high conviction, actively managed diversified portfolio of listed, quality from developed and emerging markets."
        },
        {
          "Ticker": "VBLD AU",
          "Name": "VANGUARD GLOBAL INFRA IN ETF",
          "Total Assets": 322.5438,
          "Price": 62.55,
          "1YR TR%": -3.820658,
          "3YR TR%": 6.995442,
          "Tracking Error": "9.88794",
          "Expense Ratio": "0.47",
          "Description": "Vanguard Global Infrastructure Index ETF is an exchange traded fund incorporated in Australia. The ETF seeks to track the FTSE Developed Core Infrastructure Index before taking into account fees and expenses."
        },
        {
          "Ticker": "IHD AU",
          "Name": "ISHARES S&P/ASX DIVIDEND OPP",
          "Total Assets": 295.201,
          "Price": 13.26,
          "1YR TR%": 6.670471,
          "3YR TR%": 7.147613,
          "Tracking Error": "1.50062",
          "Expense Ratio": "0.23",
          "Description": "iShares S&P/ASX Dividend Opportunities ESG Screened ETF is an exchange traded fund incorporated in Australia.The Fund aims to track the performance of an index. The index measures the performance of 50 ASX listed stocks that offer high dividend yields while meeting diversification,profitability and tradability requirements as well as being screened for sustainability considerations."
        },
        {
          "Ticker": "EMKT AU",
          "Name": "VANECK MSCI MULTIFACTOR EMER",
          "Total Assets": 64.3116719,
          "Price": 21.33,
          "1YR TR%": 19.70444,
          "3YR TR%": 7.343987,
          "Tracking Error": "7.61517",
          "Expense Ratio": "0.69",
          "Description": "VanEck MSCI Multifactor Emerging Markets ETF is an exchange-traded fund incorporated in Australia. The ETF aims to provide investment returns before fees and other costs which track the performance of the MSCI Emerging Markets Diversified Multi-factor Index(AUD)."
        },
        {
          "Ticker": "MVOL AU",
          "Name": "ISHARES EDGE MSCI AU MIN VOL",
          "Total Assets": 18.3698,
          "Price": 30.03,
          "1YR TR%": 6.856404,
          "3YR TR%": 7.417999,
          "Tracking Error": "1.82261",
          "Expense Ratio": "0.3",
          "Description": "iShares Edge MSCI Australia Minimum Volatility ETF is an exchange traded fund incorporated in Australia. The Fund seeks to track the performance of the MSCI Australia IMI Select Minimum Volatility (AUD) Index which reflects the performance characteristics of a minimum variance strategy applied to a large/mid/small cap Australian equity universe."
        },
        {
          "Ticker": "HQLT AU",
          "Name": "BETASHARES GLB QUAL LEAD ETF",
          "Total Assets": 44.76271,
          "Price": 24.82,
          "1YR TR%": 11.54168,
          "3YR TR%": 7.541653,
          "Tracking Error": "9.7084",
          "Expense Ratio": "0.38",
          "Description": "BetaShares Global Quality Leaders ETF - Currency Hedged is an exchange traded fund incorporated in Austarlia. The investment objective of the Fund is to provide an investment return that aims to track the performance of the iSTOXX MUTB Global ex-Australia Quality Leaders Index AUD Hedged, before taking into account fees and expenses."
        },
        {
          "Ticker": "AUMF AU",
          "Name": "ISHARES EDGE MSCI AUS MFACTR",
          "Total Assets": 55.62252,
          "Price": 29.94,
          "1YR TR%": 7.310755,
          "3YR TR%": 7.606755,
          "Tracking Error": "1.98888",
          "Expense Ratio": "0.3",
          "Description": "iShares Edge MSCI Australia Multifactor ETF is an exchange traded fund incorporated in Australia. The Fund seeks to track the performance of the MSCI Australia IMI Diversified Multiple-Factor (AUD) Index which is composed of Australian equities that have favorable exposure to four target style factors (quality, value, size and momentum) subject to constraints."
        },
        {
          "Ticker": "IJP AU",
          "Name": "ISHARES MSCI JAPAN",
          "Total Assets": 493.9632,
          "Price": 94.23,
          "1YR TR%": 20.33411,
          "3YR TR%": 7.622148,
          "Tracking Error": "5.71111",
          "Expense Ratio": "0.47",
          "Description": "iShares MSCI Japan ETF/AU is an exchange-traded fund incorporated in  Australia. The ETF's objective seeks to provide investment results that correspond to the performance of the Japanese market, as measured by the MSCI Japan Index. The ETF invests in a representative sample of index stocks in a variety of sectors using a market cap weighted \"portfolio sampling\" technique."
        },
        {
          "Ticker": "WVOL AU",
          "Name": "ISHARES EDGE MSCI WD MIN VOL",
          "Total Assets": 274.7359,
          "Price": 36.76,
          "1YR TR%": 9.170918,
          "3YR TR%": 7.628009,
          "Tracking Error": "7.14918",
          "Expense Ratio": "0.3",
          "Description": "iShares Edge MSCI World Minimum Volatility ETF is an exchange traded fund incorporated in Australia. The Fund seeks to track the MSCI World Minimum Volatility (AUD) Index which reflects the performance characteristics of a minimum variance strategy applied to developed market equities."
        },
        {
          "Ticker": "GRNV AU",
          "Name": "VANECK MSCI AUSTRALIAN SUSTA",
          "Total Assets": 148.6346,
          "Price": 27.65,
          "1YR TR%": 8.950378,
          "3YR TR%": 7.935425,
          "Tracking Error": "1.50997",
          "Expense Ratio": "0.35",
          "Description": "VanEck Vectors MSCI Australian Sustainable Equity ETF is an exchange traded fund incorporated in Australia. The fund aims to provide investments returns that closely track the returns of the MSCI Australian IMI Select SRI Screened Index."
        },
        {
          "Ticker": "DRUG AU",
          "Name": "BETASHARES GLOBAL HEALTHCARE",
          "Total Assets": 159.3251,
          "Price": 7.97,
          "1YR TR%": 4.668405,
          "3YR TR%": 7.98367,
          "Tracking Error": "9.52556",
          "Expense Ratio": "0.57",
          "Description": "BetaShares Global Healthcare ETF - Currency Hedged is an exchange-traded fund incorporated in Australia. The objective of the fund is to provide an investment return that aims to track the performance of the Nasdaq Global ex-Australia Healthcare Hedged AUD Index (the \"Index\"), before taking into account fees and expenses."
        },
        {
          "Ticker": "EX20 AU",
          "Name": "BETASHARES AU EX20 PORT DIVS",
          "Total Assets": 243.8717,
          "Price": 19.81,
          "1YR TR%": 6.786767,
          "3YR TR%": 8.075786,
          "Tracking Error": "1.47239",
          "Expense Ratio": "0.25",
          "Description": "BetaShares Australian Ex-20 Portfolio Diversifier ETF is an exchange traded fund incorporated in Australia. The Fund aims to track the performance of an index (before fees and expenses) which provides exposure to approximately 180 of the largest stocks listed on the Australian Securities Exchange after excluding the 20 largest, based on their market capitalisation."
        },
        {
          "Ticker": "HNDQ AU",
          "Name": "BETASHARES NASDAQ 100 ETF-H",
          "Total Assets": 273.3247,
          "Price": 31.93,
          "1YR TR%": 13.99814,
          "3YR TR%": 8.405244,
          "Tracking Error": "13.6527",
          "Expense Ratio": "0.51",
          "Description": "BetaShares NASDAQ 100 ETF - Currency Hedged is an exchange traded fund incorporated in Australia. The Fund aims to track the performance of the NASDAQ-100 Currency Hedged AUD Index (the \"Index\"), before taking into account fees and expens es. The Index includes securities of 100 of the largest U.S. and international non-financial companies listed on the NASDAQ stock market, based on market cap."
        },
        {
          "Ticker": "VSO AU",
          "Name": "VANGUARD MSCI AUS SM CO ETF",
          "Total Assets": 793.828125,
          "Price": 62.67,
          "1YR TR%": 2.04881,
          "3YR TR%": 8.525813,
          "Tracking Error": "1.28506",
          "Expense Ratio": "0.3",
          "Description": "Vanguard MSCI Australian Small Companies ETF is an exchange traded fund incorportated in Australia. The Fund seeks to match the return (income and capital appreciation) of the MSCI Australian Shares Small Cap Index before taking into account fund fees and expenses."
        },
        {
          "Ticker": "WRLD AU",
          "Name": "BETASHARES MGD RISK GLB SHAR",
          "Total Assets": 52.57451,
          "Price": 15.62,
          "1YR TR%": 9.150598,
          "3YR TR%": 8.649922,
          "Tracking Error": "8.98897",
          "Expense Ratio": "0.54",
          "Description": "BetaShares Managed Risk Global Share Fund is an exchange-traded fund incorporated in Australia. The Fund aims to provide exposure to a broadly diversified portfolio of global shares listed on the stock exchanges of the world's major developed economies and reduce the volatility of the Fund's equity investment returns and cushion downside riskdownside risk."
        },
        {
          "Ticker": "IMPQ AU",
          "Name": "EINVEST BETTER FUTURE FUND",
          "Total Assets": 41.31849,
          "Price": 4.97,
          "1YR TR%": 2.282522,
          "3YR TR%": 8.65187,
          "Tracking Error": "10.871",
          "Expense Ratio": "0.99",
          "Description": "eInvest Better Future Fund (Managed Fund) is an exchange traded fund incorporated in Australia. The Fund aims to deliver long-term capital growht predomiantely thought investments in Australian and New Zealand listed smaller companies that contribute to a sustainable future. The Fund seeks to outperform the S&P/ASX Small Ordinaries Accumulation Index."
        },
        {
          "Ticker": "INES AU",
          "Name": "INTELLIGENT INVESTOR ETHICAL",
          "Total Assets": 71.21675,
          "Price": 3,
          "1YR TR%": -4.09928,
          "3YR TR%": 8.846713,
          "Tracking Error": "#N/A N/A",
          "Expense Ratio": "0.97",
          "Description": "Intelligent Investor Ethical Share Fund (Managed Fund) is a exchange traded fund incorporated in Australia. The Fund aims to invest in a portfolio of undervalued stocks chosen on Environmental, Social and Governance (ESG) factors and financial criteria to achieve mediu to long-term capital growth."
        },
        {
          "Ticker": "WXHG AU",
          "Name": "SPDR S&P WLD EX AUS HDG CC",
          "Total Assets": 204.8,
          "Price": 21.51,
          "1YR TR%": 8.092414,
          "3YR TR%": 8.851578,
          "Tracking Error": "8.92664",
          "Expense Ratio": "0.21",
          "Description": "The SPDR S&P World ex Australia Carbon Control (Hedged) Fund is an exchange trad ed fund incorporated in Australia.The fund seeks to closely track, before fees and expenses, the returns of the S&P Developed Ex-Australia LargeMidCap Carbon Control AUD Hedged Index."
        },
        {
          "Ticker": "HETH AU",
          "Name": "BETASHARES GLB SUST LD ETF-H",
          "Total Assets": 370.8042,
          "Price": 11.99,
          "1YR TR%": 9.245935,
          "3YR TR%": 8.913078,
          "Tracking Error": "9.25617",
          "Expense Ratio": "0.62",
          "Description": "BetaShares Global Sustainability Leaders ETF - Currency Hedged is an ETF incorporated in Australia. The Fund aims to track the performance of the NASDAQ Future Global Sustainability Leaders Currency Hedged AUD Index (the \"Index\"), before taking into account fees and expenses. The index comprises a portfolio of 200 large global stocks which are climate change leaders."
        },
        {
          "Ticker": "IXI AU",
          "Name": "ISHARES GLOBAL CONSUM STAPLE",
          "Total Assets": 214.6042,
          "Price": 93.49,
          "1YR TR%": 11.14798,
          "3YR TR%": 9.060487,
          "Tracking Error": "8.09755",
          "Expense Ratio": "0.47",
          "Description": "iShares Global Consumer Staples ETF/AU is an exchange-traded fund incorporated in Australia. The Fund seeks results that correspond generally to the price and yield performance of the S&P Global Consumer Staples Index."
        },
        {
          "Ticker": "SWTZ AU",
          "Name": "SWITZER DIVIDEND GROWTH FD",
          "Total Assets": 66.98198,
          "Price": 2.54,
          "1YR TR%": 3.399017,
          "3YR TR%": 9.10456,
          "Tracking Error": "5.4967",
          "Expense Ratio": "0.89",
          "Description": "Switzer Dividend Growth Fund is an exchange traded fund incorporated in Australia. The Fund aims to provide Australian resident investors with tax effective income and long term capital growth by investing in a core portfolio of blue-chip Australian shares. The portfolio is actively managed and pays distributions quarterly."
        },
        {
          "Ticker": "ROBO AU",
          "Name": "GLOBAL X ROBO GLOBAL ROBOTIC",
          "Total Assets": 242.8333,
          "Price": 74.46,
          "1YR TR%": 18.95204,
          "3YR TR%": 9.157319,
          "Tracking Error": "8.13117",
          "Expense Ratio": "0.69",
          "Description": "Global X ROBO Global Robotics & Automation ETF is an exchange traded fund that aims to provide investors with a return that (before fees and expenses) tracks the performance of the ROBO Global Robotics and Automation Index."
        },
        {
          "Ticker": "QHAL AU",
          "Name": "VANECK MSCI INTERNATIONAL QU",
          "Total Assets": 728.2985717,
          "Price": 39.22,
          "1YR TR%": 12.52273,
          "3YR TR%": 9.224672,
          "Tracking Error": "9.82318",
          "Expense Ratio": "0.43",
          "Description": "VanEck Vectors MSCI World ex Australia Quality (Hedged) ETF is an exchange-traded fund incorporated in Australia. The ETF aims to provide investment returns before fees and other costs which track the performance of its Reference Index in Australian dollars."
        },
        {
          "Ticker": "IHVV AU",
          "Name": "ISHARES S&P 500 AUD HEDGED",
          "Total Assets": 1150.766,
          "Price": 41.84,
          "1YR TR%": 7.648267,
          "3YR TR%": 9.373113,
          "Tracking Error": "11.0617",
          "Expense Ratio": "0.1",
          "Description": "iShares S&P 500 AUD Hedged ETF is an exchange-traded fund incorporated in Australia. The Fund aims to provide investors with the performance of the market, before fees and expenses (including the cost of hedging), as represented by an index composed of large capitalisation U.S. equities (hedged to Australian dollars)."
        },
        {
          "Ticker": "VGAD AU",
          "Name": "VANGUARD MSCI IND INTL SH HG",
          "Total Assets": 2487.511,
          "Price": 87.43,
          "1YR TR%": 8.865649,
          "3YR TR%": 9.504581,
          "Tracking Error": "8.83659",
          "Expense Ratio": "0.21",
          "Description": "Vanguard MSCI Index International Shares Hedged ETF is an exchange traded fund incorporated in Australia. The Fund seeks to track the return of the MSCI World ex-Australia (with net dividends reinvested), hedged into Australian dollars Index, before taking into account fees, expenses and tax."
        },
        {
          "Ticker": "WDIV AU",
          "Name": "SPDR S&P GLOBAL DIVIDEND FUN",
          "Total Assets": 359.73,
          "Price": 17.73,
          "1YR TR%": 5.314427,
          "3YR TR%": 9.675581,
          "Tracking Error": "5.01792",
          "Expense Ratio": "0.5",
          "Description": "SPDR S&P Global Dividend Fund is an exchange-traded fund which tracks the performance of the S&P Global Dividend Aristocrats Index. The Index measures the performance of the highest dividend yielding companies within the S&P Global Broad Market Index that have followed a policy of increasing or stable dividends for at least 10 years."
        },
        {
          "Ticker": "YMAX AU",
          "Name": "BETASHARES AUS TOP 20 EQ YLD",
          "Total Assets": 404.8673,
          "Price": 7.54,
          "1YR TR%": 11.69176,
          "3YR TR%": 10.04435,
          "Tracking Error": "3.05352",
          "Expense Ratio": "0.69",
          "Description": "BetaShares Australian Top 20 Equity Yield Maximiser Fund is an exchange-traded fund incorporated in Australia. The Fund aims to provide investors with exposure to a basket of 20 blue-chip Australian equities. The Fund will seek to achieve these objectives by combining an investment portfolio comprising the equity securities that make up the S&P/ASX20 Index along with call options."
        },
        {
          "Ticker": "MSTR AU",
          "Name": "MORNINGSTAR INTL SHARES ACT",
          "Total Assets": 158.5676,
          "Price": 8.79,
          "1YR TR%": 12.28107,
          "3YR TR%": 10.31443,
          "Tracking Error": "9.4109",
          "Expense Ratio": "0.39",
          "Description": "Morningstar International Shares Active ETF (Managed Fund) is a exchange traded fund incorporated in Australia. The Fund invest predominaantly in units of the Morningstar International Shares (Hedged) Fund and some cash. The unlerying Fund invests in listed international shares with the aim of producing superior long-term returns relative to the benchmark."
        },
        {
          "Ticker": "IVE AU",
          "Name": "ISHARES MSCI ETF",
          "Total Assets": 424.1477,
          "Price": 110.87,
          "1YR TR%": 21.67839,
          "3YR TR%": 10.41078,
          "Tracking Error": "6.67556",
          "Expense Ratio": "0.31",
          "Description": "iShares MSCI EAFE ETF/AU is an exchange-traded fund incorporated in Australia. The ETF tracks the performance of the MSCI EAFE Index. The ETF holds large and mid-cap stocks. Its investments are focused on developed countries across the world excluding the U.S. and Canada. The ETF weights the holdings using a market capitalization methodology."
        },
        {
          "Ticker": "EINC AU",
          "Name": "BETAS MARTN CURIE EQT INC FD",
          "Total Assets": 23.31698,
          "Price": 8.42,
          "1YR TR%": 5.146241,
          "3YR TR%": 10.41135,
          "Tracking Error": "5.40246",
          "Expense Ratio": "0.85",
          "Description": "BetaShares  Martin Currie Equity Income Fund (Managed Fund) is a exchange traded  fund incorporated in Australia. The Fund aims to provide an after-tax income yield above that of the S&P/ASX 200 Index by investing in a portfolio of listed Australian equities and to grow this income above the rate of inflation (as measured by the Consumer Price Index) over the long term."
        },
        {
          "Ticker": "RARI AU",
          "Name": "RUSSELL INVEST AUST RESPONSI",
          "Total Assets": 319.2999,
          "Price": 24.95,
          "1YR TR%": 4.199812,
          "3YR TR%": 10.44264,
          "Tracking Error": "2.0587",
          "Expense Ratio": "0.45",
          "Description": "Russell Australian Responsible Investment ETF is an exchange-traded fund incorporated in Australia. The Fund seeks to track the performance of the Russell Australia ESG High Dividend Index."
        },
        {
          "Ticker": "QLTY AU",
          "Name": "BETASHARES GB QUAL LEADERS",
          "Total Assets": 383.2315002,
          "Price": 24.91,
          "1YR TR%": 21.51682,
          "3YR TR%": 10.49091,
          "Tracking Error": "8.1288",
          "Expense Ratio": "0.35",
          "Description": "BetaShares Global Quality Leaders ETF is a exchanged traded fund incorporated in Australia. The Fund aims provide an investment return that aims to track the performance of the iSTOXX MUTB Global ex-Australia Quality Leaders 150 Index (the \"Index\"), before taking into account fees and expenses."
        },
        {
          "Ticker": "VAS AU",
          "Name": "VANGUARD AUST SHARES IDX ETF",
          "Total Assets": 12479.46,
          "Price": 91.08,
          "1YR TR%": 9.402785,
          "3YR TR%": 10.49656,
          "Tracking Error": "0.444315",
          "Expense Ratio": "0.07",
          "Description": "Vanguard Australian Shares Index ETF is an exchange traded fund incorporated in Australia. The Fund seeks to match the total return of the S&P/ASX 300 Index before taking into account fees and expenses."
        },
        {
          "Ticker": "IOZ AU",
          "Name": "ISHARES CORE S&P/ASX 200 ETF",
          "Total Assets": 4411.584416,
          "Price": 29.65,
          "1YR TR%": 10.00839,
          "3YR TR%": 10.5147,
          "Tracking Error": "0.409989",
          "Expense Ratio": "0.05",
          "Description": "iShares Core S&P/ASX 200 ETF is an exchange traded fund incorporated in Australia. The Fund seeks to track the performance of the S&P/ASX 200 Index investing in the 200 largest companies in Australia."
        },
        {
          "Ticker": "STW AU",
          "Name": "SPDR S&P/ASX 200 FUND",
          "Total Assets": 4794.85,
          "Price": 66.36,
          "1YR TR%": 10.02829,
          "3YR TR%": 10.52113,
          "Tracking Error": "0.446965",
          "Expense Ratio": "0.13",
          "Description": "SPDR S&P/ASX 200 Fund is an exchange traded fund which tracks the performance of the S&P/ASX 200 Index. The Fund will invest in the securities comprising the Index in proportion to their relative weightings. The Index is comprised of the 200 largest securities by market capitalization and most liquid securities in Australia."
        },
        {
          "Ticker": "SFY AU",
          "Name": "SPDR S&P/ASX 50 FUND",
          "Total Assets": 826.55,
          "Price": 65.1,
          "1YR TR%": 10.74378,
          "3YR TR%": 10.52322,
          "Tracking Error": "1.25288",
          "Expense Ratio": "0.286",
          "Description": "SPDR S&P/ASX 50 Fund is an exchange traded fund incorporated in Australia which tracks the performance of the S&P/ASX 50 Index. The Fund will invest in the securities comprising the Index in proportion to their relative weightings. The Index is comprised of the 50 largest securities by market capitalization and most liquid securities in Australia."
        },
        {
          "Ticker": "IXJ AU",
          "Name": "ISHARES GLOBAL HEALTHCAR/AU",
          "Total Assets": 1325.831,
          "Price": 131.36,
          "1YR TR%": 12.37287,
          "3YR TR%": 10.66606,
          "Tracking Error": "15.8712",
          "Expense Ratio": "0.47",
          "Description": "iShares Global Healthcare ETF/AU is an exchange-traded fund incorporated in Australia. The ETF tracks the S&P Global Healthcare Index. The ETF holds global large-cap health care stocks. Its investments are focused in pharmaceutical, bio tech, and medical device companies; with its largest allocation to the United St ates. A market capitalization methodology is used for weighting."
        },
        {
          "Ticker": "ESGI AU",
          "Name": "VANECK MSCI INTERNATIONAL SU",
          "Total Assets": 158.85,
          "Price": 30.55,
          "1YR TR%": 18.98343,
          "3YR TR%": 10.71765,
          "Tracking Error": "6.04951",
          "Expense Ratio": "0.55",
          "Description": "VanEck Vectors MSCI International Sustainable Equity ETF is an exchange-traded fund incorporated in Australia.  The ETF aims to provide investment returns before fees and other costs which track the performance of its Reference Index in Australian dollars."
        },
        {
          "Ticker": "A200 AU",
          "Name": "BETASHARES AUSTRALIA 200 ETF",
          "Total Assets": 3186.742143,
          "Price": 122.3,
          "1YR TR%": 10.04022,
          "3YR TR%": 10.85468,
          "Tracking Error": "0.535441",
          "Expense Ratio": "0.04",
          "Description": "BetaShares Australia 200 ETF is an exchange traded fund incorporated in Australia. The Fund aims to tracks the performance of the Solactive Australia 200 Index (the \"Index\"), before taking into account fees and expenses. The Index is designed to provide exposure to 200 of the largest companies listed on the ASX, based on their free float-adjusted market capitalisation."
        },
        {
          "Ticker": "IHOO AU",
          "Name": "ISHARES GLOBAL 100 AUD HEDGE",
          "Total Assets": 311.2391,
          "Price": 138.79,
          "1YR TR%": 8.131517,
          "3YR TR%": 10.8727,
          "Tracking Error": "9.38298",
          "Expense Ratio": "0.43",
          "Description": "iShares Global 100 AUD Hedged ETF is an exchange-traded fund incorporated in Australia. The Fund aims to provide investors with the performance of the market, before fees and expenses (including the cost of hedging), as represented by an index composed of 100 large capitalisation global equities (hedged to Australian dollars)."
        },
        {
          "Ticker": "HEUR AU",
          "Name": "BETASHARES EUROPE ETF - CURR",
          "Total Assets": 44.40946267,
          "Price": 13.02,
          "1YR TR%": 15.52795,
          "3YR TR%": 10.93356,
          "Tracking Error": "10.6696",
          "Expense Ratio": "0.56",
          "Description": "Betashares Europe ETF - Currency Hedged is an exchange traded fund incorporated in Australia. The Fund aims to provide an exposure to the equity securities that makeup the S&P Eurozone Exporters Hedged AUD Index, hedged for any change in the value of the EUR relative to the Australian Dollar."
        },
        {
          "Ticker": "VEQ AU",
          "Name": "VANGUARD FTSE EUROPE SHARES",
          "Total Assets": 238.1926,
          "Price": 67.78,
          "1YR TR%": 23.90871,
          "3YR TR%": 11.02461,
          "Tracking Error": "9.48072",
          "Expense Ratio": "0.35",
          "Description": "Vanguard FTSE Europe Shares ETF is an exchange-traded fund incorporated in Australia. The fund seeks to track the return of the FTSE Developed Europe All Cap Index (with net dividends reinvested) in Australian dollars, before taking into account fees, expenses and tax."
        },
        {
          "Ticker": "PIXX AU",
          "Name": "PLATINUM INTERNATIONAL FUND",
          "Total Assets": 324.9088,
          "Price": 4.78,
          "1YR TR%": 19.00042,
          "3YR TR%": 11.15664,
          "Tracking Error": "#N/A N/A",
          "Expense Ratio": "1.1",
          "Description": "Platinum International Fund ETF is an exchange-traded fund incorporated in Australia. The PIXX will primarily invest in units of the Platinum International Fund (\"PIF\" or \"Underlying Fund\"), and some cash."
        },
        {
          "Ticker": "MVW AU",
          "Name": "VANECK AUSTRALIAN EQUAL WEIG",
          "Total Assets": 1914.557,
          "Price": 34.94,
          "1YR TR%": 12.28357,
          "3YR TR%": 11.20915,
          "Tracking Error": "3.06963",
          "Expense Ratio": "0.35",
          "Description": "VanEck Vectors Australian Equal Weight ETF is an exchange-traded fund incorporated in Australia. The Fund aims to provide investment returns that closely track the returns of the MVIS Australia Equal Weight Index."
        },
        {
          "Ticker": "E200 AU",
          "Name": "SPDR S&P/ASX 200 ESG FUND",
          "Total Assets": 38.33,
          "Price": 23.4,
          "1YR TR%": 9.96417,
          "3YR TR%": 11.22996,
          "Tracking Error": "2.7136",
          "Expense Ratio": "0.13",
          "Description": "SPDR S&P/ASX 200 ESG Fund is an exchange traded fund incorporated in Australia. The Fund aims to track the S&P/ASX 200 ESG Index which is a broad-based, market-cap-weighted index that is designed to measure the performance of securities meeting sustainability criteria, while maintaining similar overall industry group weights as the S&P/ASX 200 index."
        },
        {
          "Ticker": "IHWL AU",
          "Name": "ISHARES MSCI WLD X OZ ESG",
          "Total Assets": 237.7247,
          "Price": 41.87,
          "1YR TR%": 10.3398,
          "3YR TR%": 11.3156,
          "Tracking Error": "9.39385",
          "Expense Ratio": "0.12",
          "Description": "iShares Core MSCI World ex Aus ESG AUD Hedged ETF is an ETF incorporatedin Australia.The Fund aims to provide investors with the performance of the MSCI World Ex Aus Custom ESG Leaders Index 100% Hedged to AUD,before fees&expenses. The index is designed to measure the AUD hedged performance of global, developed  market large and mid-cap comanies with better sustainbility credentials."
        },
        {
          "Ticker": "TECH AU",
          "Name": "GLOBAL X MORNINGSTAR GLOBAL",
          "Total Assets": 328.03,
          "Price": 94.51,
          "1YR TR%": 19.09472,
          "3YR TR%": 11.40725,
          "Tracking Error": "11.067",
          "Expense Ratio": "0.45",
          "Description": "Global X Morningstar Global Technology ETF is an exchange-traded fund incorporated  in Australia. The Fund aims to provide investors with a return that (before feesand expenses) tracks the performance of the Morningstar Developed Markets Technology Moat Focus Index."
        },
        {
          "Ticker": "DHHF AU",
          "Name": "BETA DIV ALL GROWTH ETF",
          "Total Assets": 259.8199,
          "Price": 30.07,
          "1YR TR%": 14.10808,
          "3YR TR%": 11.49865,
          "Tracking Error": "#N/A N/A",
          "Expense Ratio": "0.19",
          "Description": "Betashares Diversified All Growth ETF is a exchange traded fund incorporated in Australia. The Fund will aim to provide investors with a broadly diversified portfolio consistent with a high growth risk-return profile and passively blend the returns of the index-tracking Underlying ETFs in which the Fund invests, in proportion to the Fund's strategic asset allocation, before fees and expenses."
        },
        {
          "Ticker": "ILC AU",
          "Name": "ISHARES S&P/ASX 20 ETF",
          "Total Assets": 525.0416,
          "Price": 28.21,
          "1YR TR%": 10.61057,
          "3YR TR%": 11.49925,
          "Tracking Error": "1.48444",
          "Expense Ratio": "0.24",
          "Description": "iShares S&P/ASX 20 ETF is an exchange-traded fund incorporated in Australia. The Fund seeks to track the performance of the S&P/ASX 20 Index investing in the twenty largest blue chip companies in Australia."
        },
        {
          "Ticker": "SYI AU",
          "Name": "SPDR MSCI AUS SELECT DVD",
          "Total Assets": 405.3,
          "Price": 27.63,
          "1YR TR%": 8.063354,
          "3YR TR%": 11.62536,
          "Tracking Error": "1.43803",
          "Expense Ratio": "0.35",
          "Description": "SPDR MSCI Australia Select High Dividend Yield Fund is an exchange-traded fund incorporated in Australia. The Fund seeks to track the performance of the MSCI Australia Select High Dividend Yield Index."
        },
        {
          "Ticker": "VESG AU",
          "Name": "VGD ETHIC CONS INTL SH IDX",
          "Total Assets": 719.2896,
          "Price": 76.33,
          "1YR TR%": 17.29,
          "3YR TR%": 11.6652,
          "Tracking Error": "8.49029",
          "Expense Ratio": "0.18",
          "Description": "Vanguard Ethically Conscious International Shares Index ETF is an exchange-traded product incorporated in Australia. The Fund aims to track the return of the FTSE Developed ex-Australia ex Non-renewable Energy/Vice Products/Weapons Net Tax Index before taking into account fees, expenses and tax."
        },
        {
          "Ticker": "VISM AU",
          "Name": "VANGUARD MSCI INTL SML CO IX",
          "Total Assets": 264.2452,
          "Price": 59.64,
          "1YR TR%": 12.77697,
          "3YR TR%": 11.66882,
          "Tracking Error": "8.71471",
          "Expense Ratio": "0.32",
          "Description": "Vanguard MSCI International Small Companies Index ETF is an exchange traded fund incorporated in Australia. The ETF seeks to track the MSCI Developed World ex-Australia Small Cap Index before taking into account fees and expenses."
        },
        {
          "Ticker": "EIGA AU",
          "Name": "EINVEST INCOME GENERATOR FD",
          "Total Assets": 31.89188,
          "Price": 3.71,
          "1YR TR%": 10.16829,
          "3YR TR%": 11.8281,
          "Tracking Error": "4.59074",
          "Expense Ratio": "0.8",
          "Description": "eInvest Income Generator Fund (Managed Fund) is an exchanged traded fund incorporated in Australia. The Fund invests in ASX300 stocks with the objective of providing investors with tax effective income paid via monthly distributions."
        },
        {
          "Ticker": "WDMF AU",
          "Name": "ISHARES EDGE MSCI WLD MFACTR",
          "Total Assets": 150.6204,
          "Price": 38.57,
          "1YR TR%": 15.00853,
          "3YR TR%": 11.83428,
          "Tracking Error": "8.2772",
          "Expense Ratio": "0.35",
          "Description": "iShares Edge MSCI World Multifactor ETF is an exchange traded fund incorporated in Australia. The Fund seeks to track the performance of MSCI World Diversified Multiple-Factor (AUD) Index which is composed of developed market equities that have favorable exposure to four target style factors (quality, value, size and momentum)"
        },
        {
          "Ticker": "VLC AU",
          "Name": "VANGUARD MSCI AUS LARGE CO",
          "Total Assets": 203.6857507,
          "Price": 73.11,
          "1YR TR%": 10.52475,
          "3YR TR%": 11.86239,
          "Tracking Error": "1.26953",
          "Expense Ratio": "0.2",
          "Description": "Vanguard MSCI Australian Large Companies ETF is an exchange traded fund incorportated in Australia. The Fund seeks to match the return (income and capital appreciation) of the MSCI Australian Shares Large Cap Index before taking into account fund fees and expenses"
        },
        {
          "Ticker": "HACK AU",
          "Name": "BETASHARES GLOBAL CYBERSECUR",
          "Total Assets": 737.6379,
          "Price": 9.44,
          "1YR TR%": 9.006926,
          "3YR TR%": 11.91986,
          "Tracking Error": "13.0948",
          "Expense Ratio": "0.67",
          "Description": "Betashares Global Cybersecurity ETF is an exchange-traded fund incorporated in Australia. The investment objective of the Fund is to provide an investment return that aims to track the performance of the Nasdaq CTA Cybersecurity Index (the \"Index\"), before taking into account fees and expenses."
        },
        {
          "Ticker": "RDV AU",
          "Name": "RUSSELL INVEST HIGH DIV AUST",
          "Total Assets": 251.5776,
          "Price": 28.77,
          "1YR TR%": 7.290938,
          "3YR TR%": 11.92024,
          "Tracking Error": "1.34876",
          "Expense Ratio": "0.34",
          "Description": "Russell Invest High Div Australian Shares ETF is an exchange-traded fund incorporated in Australia. The Fund seeks to track the performance of the Russell Australia High Dividend Index by investing predominantly in Australian shares and trusts listed on the ASX. The index is weighted to companies that are expected to make high dividend payments."
        },
        {
          "Ticker": "IEU AU",
          "Name": "ISHARES EUROPE/AU",
          "Total Assets": 789.6643,
          "Price": 77.46,
          "1YR TR%": 24.67654,
          "3YR TR%": 11.95403,
          "Tracking Error": "8.81505",
          "Expense Ratio": "0.6",
          "Description": "iShares Europe ETF/AU is an exchange-traded fund incorporated in Australia. The Fund seeks investment results that correspond to the performance of the S&P Europe 350 Index."
        },
        {
          "Ticker": "IIND AU",
          "Name": "BETASHARES INDIA QUALITY ETF",
          "Total Assets": 86.50212,
          "Price": 10.45,
          "1YR TR%": 7.997093,
          "3YR TR%": 11.98819,
          "Tracking Error": "8.51898",
          "Expense Ratio": "0.8",
          "Description": "BetaShares India Quality ETF is an exchange-traded fund incorporated in Australia. The Fund aims to provide an investment return that aims to track the performance of the Solactive India Quality Select Index NTR, before taking into account fees, expenses and taxes."
        },
        {
          "Ticker": "WXOZ AU",
          "Name": "SPDR S&P WLD EX AUS C CONTRO",
          "Total Assets": 336.35,
          "Price": 39.13,
          "1YR TR%": 17.61234,
          "3YR TR%": 12.08841,
          "Tracking Error": "8.40717",
          "Expense Ratio": "0.18",
          "Description": "SPDR S&P World ex Australia Carbon Control Fund is an exchange traded fund incorporated in Australia.The fund seeks to closely track, before fees and expenses, the returns of the S&P Developed Ex-Australia LargeMidCap Carbon Control Index (AUD)."
        },
        {
          "Ticker": "AGX1 AU",
          "Name": "ANTIPODES GLBL SHRS EQMF ETF",
          "Total Assets": 0.000023,
          "Price": 5.45,
          "1YR TR%": 22.06829,
          "3YR TR%": 12.24601,
          "Tracking Error": "10.1648",
          "Expense Ratio": "1.1",
          "Description": "Antipodes Global Shares (Quoted Managed Fund) is an exchange-traded fund (ETF) in Australia. The Fund typically invests in a select number of attractively valued companies listed on global share markets (usually a minimum of 30 holdings). The Fund is also permitted to utilise exchange traded derivatives for risk management purposes and to achieve equity exposure."
        },
        {
          "Ticker": "BNKS AU",
          "Name": "BETASHARES GLB BANKS-CURR HG",
          "Total Assets": 44.69624,
          "Price": 6.24,
          "1YR TR%": 6.337444,
          "3YR TR%": 12.3225,
          "Tracking Error": "9.43641",
          "Expense Ratio": "0.57",
          "Description": "BetaShares Global Banks ETF - Currency Hedged is an exchange-traded fund incorporated in Australia. the objective of the fund is to provide an investment return that aims to track the performance of the Nasdaq Global ex-Australia Banks Hedged AUD Index (the \"Index\"), before taking into account fees and expenses."
        },
        {
          "Ticker": "MVE AU",
          "Name": "VANECK S&P/ASX MIDCAP ETF",
          "Total Assets": 195.5871,
          "Price": 37.19,
          "1YR TR%": 8.172895,
          "3YR TR%": 12.4611,
          "Tracking Error": "1.90053",
          "Expense Ratio": "0.45",
          "Description": "VanEck Vectors S&P/ASX MidCap ETF is an exchange-traded fund incorporated in Australia.  The fund aims to provide investment returns that closely track the returns of the S&P/ASX Midcap 50 Index"
        },
        {
          "Ticker": "AASF AU",
          "Name": "AIRLIE AUSTRALIAN SHARE FUND",
          "Total Assets": 386.9427,
          "Price": 3.45,
          "1YR TR%": 10.68579,
          "3YR TR%": 12.59708,
          "Tracking Error": "5.8334",
          "Expense Ratio": "#N/A N/A",
          "Description": "Airlie Australian Share Fund is a unit trust incorporated in Australia. The Fund aims to provide long-term capital growth and regular income through investment in Australian equities. The Fund uses the long only, bottom up strategy by investing in Australian equities fund to track S&P/ASX 200 Accumulation Index. (Parent Fund MGE9705 AU Equity)"
        },
        {
          "Ticker": "ETHI AU",
          "Name": "BETASHARES GLOBAL SUSTAINABI",
          "Total Assets": 2606.048,
          "Price": 12.53,
          "1YR TR%": 18.93305,
          "3YR TR%": 12.82175,
          "Tracking Error": "8.7995",
          "Expense Ratio": "0.59",
          "Description": "BetaShares Global Sustainability Leaders ETF is an exchange-traded fund incorporated in Australia. The investment objective of the Fund is to provide an investment the return that aims to track the performance of the Nasdaq Future Global Sustainability Leaders Index (the \"Index\"), before taking into account fees and expenses."
        },
        {
          "Ticker": "ESTX AU",
          "Name": "GLOBAL X EURO STOXX 50 ETF",
          "Total Assets": 92.1897,
          "Price": 82.07,
          "1YR TR%": 36.83175,
          "3YR TR%": 12.86329,
          "Tracking Error": "10.8773",
          "Expense Ratio": "0.35",
          "Description": "Global X EURO STOXX 50� ETF is an exchange-traded fund incorporated in Australia. The fund aims to provide investors with a return that (before fees and expenses) tracks the performance of the EURO STOXX 50 Index."
        },
        {
          "Ticker": "INCM AU",
          "Name": "BETASHARES GB INCOME LEADERS",
          "Total Assets": 27.98927,
          "Price": 15.68,
          "1YR TR%": 9.447246,
          "3YR TR%": 12.8673,
          "Tracking Error": "8.42369",
          "Expense Ratio": "0.45",
          "Description": "BetaShares Global Income Leaders ETF is a exchanged traded fund incorporated in Australia. The Fund aims to provide an investment return that aims to track the performance of the Nasdaq Global Income Leaders Index (the \"Index\"), before taking into account fees and expenses."
        },
        {
          "Ticker": "QMIX AU",
          "Name": "SPDR MSCI WORLD QUALITY MIX",
          "Total Assets": 44.95,
          "Price": 26.9,
          "1YR TR%": 17.53651,
          "3YR TR%": 12.98848,
          "Tracking Error": "7.59983",
          "Expense Ratio": "0.4",
          "Description": "SPDR MSCI World Quality Mix Fund is an exchange-traded fund incorporated in Australia. The Fund seeks to provide investment results that, before fees and expenses, correspond generally to the return performance of the MSCI World Quality Mix Index, assuming all payment from the index constituents are reinvested."
        },
        {
          "Ticker": "VGS AU",
          "Name": "VANGUARD MSCI IND INTL ETF",
          "Total Assets": 6231.327,
          "Price": 108.85,
          "1YR TR%": 18.25023,
          "3YR TR%": 13.27946,
          "Tracking Error": "8.20116",
          "Expense Ratio": "0.18",
          "Description": "Vanguard MSCI Index International Shares ETF is an exchange traded fund incorporated in Australia. The Fund seeks to track the return of the MSCI World ex-Australia (with net dividends reinvested), in Australian dollars Index, before taking into account fees, expenses and tax."
        },
        {
          "Ticker": "F100 AU",
          "Name": "BETASHARES FTSE 100 ETF",
          "Total Assets": 452.6692,
          "Price": 11.22,
          "1YR TR%": 18.01983,
          "3YR TR%": 13.38889,
          "Tracking Error": "9.98383",
          "Expense Ratio": "0.45",
          "Description": "Betashares FTSE 100 ETF is a exchange traded fund incorporated in Australia. The Fund aims to track the performance of the FTSE 100 Index, before taking into account fees and expenses"
        },
        {
          "Ticker": "QOZ AU",
          "Name": "BETASHARES FTSE RAFI AU 200",
          "Total Assets": 434.3402681,
          "Price": 14.7,
          "1YR TR%": 10.2537,
          "3YR TR%": 13.39162,
          "Tracking Error": "1.38499",
          "Expense Ratio": "0.4",
          "Description": "BetaShares FTSE RAFI Australia 200 ETF is an exchange-traded fund incorporated in Australia. The Fund aims to closely track the performance of the FTSE RAFI Australia 200 Index."
        },
        {
          "Ticker": "UMAX AU",
          "Name": "BETASHARES S&P 500 YIELD MAX",
          "Total Assets": 148.0761,
          "Price": 21.78,
          "1YR TR%": 15.36919,
          "3YR TR%": 13.59039,
          "Tracking Error": "10.8603",
          "Expense Ratio": "0.79",
          "Description": "BetaShares S&P 500 Yield Maximiser Fund is an exchange-traded managed fund incorporated in Australia. The Fund aims to provide an exposure to the equity securities that make up the S&P 500 Index plus regular income from call options that are written on the Fund's exposure to the Index."
        },
        {
          "Ticker": "QUAL AU",
          "Name": "VANECK MSCI INTERNATIONAL QU",
          "Total Assets": 3970.3,
          "Price": 45.41,
          "1YR TR%": 23.38789,
          "3YR TR%": 13.67725,
          "Tracking Error": "9.23239",
          "Expense Ratio": "0.4",
          "Description": "VanEck Vectors MSCI World ex Australia Quality ETF is an exchange-traded fund incorporated in Australia. The ETF aims to provide investment returns that closely track the returns of the MSCI World ex Australia Quality Index."
        },
        {
          "Ticker": "ZYUS AU",
          "Name": "GLOBAL X S&P 500 HIGH YIELD",
          "Total Assets": 68.43312,
          "Price": 13.15,
          "1YR TR%": 2.654232,
          "3YR TR%": 13.76991,
          "Tracking Error": "10.0551",
          "Expense Ratio": "0.35",
          "Description": "Global X S&P 500 High Yield Low Volatility ETF is an exchange-traded fund incorporated in Australia. The Fund aims to provide investors with a return that (before fees and expenses) tracks the performance of the S&P 500 Low Volatility High Dividend Index (the Index)."
        },
        {
          "Ticker": "GGUS AU",
          "Name": "BETASHARES GEAR US EQT CUR H",
          "Total Assets": 173.6955,
          "Price": 27.35,
          "1YR TR%": 8.316833,
          "3YR TR%": 14.25562,
          "Tracking Error": "31.0393",
          "Expense Ratio": "0.8",
          "Description": "Betashares Geared US Equity Fund - Currency Hedged is an exchange-traded fund incorporated in Australia. The Fund aims to provide geared exposure, before fees and expenses, that closely tracks the return of the US Share markets, hedged to the Australian dollar. The Fund will only invest in US ETFs are listed for trading on major North Amercian Stock exchange with min fund size of US$5 bil."
        },
        {
          "Ticker": "MVR AU",
          "Name": "VANECK AUSTRALIAN RESOURCES",
          "Total Assets": 387.4408,
          "Price": 38.21,
          "1YR TR%": 23.83701,
          "3YR TR%": 14.28182,
          "Tracking Error": "1.61425",
          "Expense Ratio": "0.35",
          "Description": "VanEck Vectors Australian Resources ETF is an exchange-traded fund incorporated in Australia. The Fund aims to provide investment returns that closely track the returns of the MVIS Australia Resources Index."
        },
        {
          "Ticker": "FOOD AU",
          "Name": "BETASHARES GLB AGRI COMPANIE",
          "Total Assets": 123.4715,
          "Price": 7.25,
          "1YR TR%": -1.589341,
          "3YR TR%": 14.34882,
          "Tracking Error": "11.0655",
          "Expense Ratio": "0.57",
          "Description": "BetaShares Global Agriculture Companies ETF - Currency Hedged is an exchange-traded fund incorporated in Australia. The objective of the fund is to provide an investment return that aims to track the performance of the Nasdaq Global ex-Australia Agriculture Companies Hedged AUD Index (the \"Index\"), before taking into account fees and expenses."
        },
        {
          "Ticker": "QFN AU",
          "Name": "BETASHARES AU FINC SEC ETF",
          "Total Assets": 41.0026,
          "Price": 11.91,
          "1YR TR%": 6.298083,
          "3YR TR%": 14.35274,
          "Tracking Error": "1.62547",
          "Expense Ratio": "0.34",
          "Description": "BetaShares Australia Financials Sector ETF is an exchange traded fund incorporated in Australia. The Fund seeks to track the performance of the Solactive Australia Financials Ex-REITs Sector Index. This Index is a subset of the Solactive Australia 200 Index and comprises the shares of the largest companies involved in the financials sector listed on the ASX."
        },
        {
          "Ticker": "VHY AU",
          "Name": "VANGUARD AUS HIGH YIELD",
          "Total Assets": 3067.796,
          "Price": 68.78,
          "1YR TR%": 12.61424,
          "3YR TR%": 14.35728,
          "Tracking Error": "0.826854",
          "Expense Ratio": "0.25",
          "Description": "Vanguard Australian Shares High Yield ETF is an exchange traded fund incorportated in Australia. The Fund seeks to match the return (income and capital appreciation) of the FTSE ASFA Australia High Dividend Yield Index before fees and expenses."
        },
        {
          "Ticker": "NDQ AU",
          "Name": "BETASHARES NASDAQ 100 ETF",
          "Total Assets": 3427.958,
          "Price": 35.12,
          "1YR TR%": 24.51697,
          "3YR TR%": 14.4531,
          "Tracking Error": "12.6255",
          "Expense Ratio": "0.48",
          "Description": "BetaShares NASDAQ 100 is an exchange-traded managed fund that trades on the Australian Securities Exchange. The Fund aims to provide an exposure to the equity securities that make up the NASDAQ 100 Index."
        },
        {
          "Ticker": "OZF AU",
          "Name": "SPDR S&P/ASX 200 FINANCIALS",
          "Total Assets": 115.06,
          "Price": 21.07,
          "1YR TR%": 6.165115,
          "3YR TR%": 14.46597,
          "Tracking Error": "1.66265",
          "Expense Ratio": "0.34",
          "Description": "SPDR S&P/ASX 200 Financials Ex A-REIT Fund is an exchange traded fund. The ETF provides investors an interest in a diversified portfolio of Australian listed securities, reflecting or closely tracking (before fees and expenses) the S&P/ASX 200 Financials x-A REIT Index comprising shares in companies in the S&P/ASX 200 Index involved in the financial sector excluding REITs."
        },
        {
          "Ticker": "OZR AU",
          "Name": "SPDR S&P/ASX 200 RESOURCES F",
          "Total Assets": 147.46,
          "Price": 13.73,
          "1YR TR%": 24.31579,
          "3YR TR%": 14.51086,
          "Tracking Error": "1.84226",
          "Expense Ratio": "0.34",
          "Description": "SPDR S&P/ASX 200 Resources Fund is an exchange traded fund. The ETF provides investors an interest in a diversified portfolio of Australian listed securities, reflecting or closely tracking (before fees and expenses) the S&P/ASX 200 Resources Index comprising shares in companies in the S&P/ASX 200 Index involved in the metals and mining industry and energy."
        },
        {
          "Ticker": "IVV AU",
          "Name": "ISHARES S&P 500 ETF/AUS",
          "Total Assets": 6033.589844,
          "Price": 45.73,
          "1YR TR%": 17.55005,
          "3YR TR%": 15.0301,
          "Tracking Error": "9.72696",
          "Expense Ratio": "0.04",
          "Description": "iShares Core S&P 500 ETF is an exchange-traded fund incorporated in the Australia. The ETF tracks the performance of the S&P 500 Index. The Fund invests in all 500 stocks that comprise the index. The ETF holds predominantly large-cap stocks from U.S. companies. The Fund weights the holdings using a market capitalization methodology and rebalances quarterly."
        },
        {
          "Ticker": "IWLD AU",
          "Name": "ISHARES MSCI WLD X OZ ESG",
          "Total Assets": 683.0196645,
          "Price": 46.5,
          "1YR TR%": 19.80723,
          "3YR TR%": 15.18998,
          "Tracking Error": "8.8468",
          "Expense Ratio": "0.09",
          "Description": "The iShares Core MSCI World Ex Aus ESG ETF is an exchange-traded fund incorporat ed in Australia. The Fund aims to provide investors with the performan-ce of the  MSCI World Ex Aus Custom ESG Leaders Index, before fees&expenses. The index is designed to measure the performance of global, developed market large  and mid-c ap companies with better sustainbility credentials relative to peers."
        },
        {
          "Ticker": "QRE AU",
          "Name": "BETASHARES S&P/ASX 200 RESOU",
          "Total Assets": 180.34375,
          "Price": 7.83,
          "1YR TR%": 24.45533,
          "3YR TR%": 15.28494,
          "Tracking Error": "2.2837",
          "Expense Ratio": "0.34",
          "Description": "BetaShares Australian Rescource is an exchange traded fund incorporated in Australia. The Fund seeks to track the performance of the Solactive Australia Re sources Sector Index. This Index is a subset of the Solactive Australia 200 Index and comprises the shares of the largest companies involved in the resouce industry listed on the ASX."
        },
        {
          "Ticker": "IOO AU",
          "Name": "ISHARES GLOBAL 100/AU",
          "Total Assets": 2847.514,
          "Price": 114.95,
          "1YR TR%": 18.74596,
          "3YR TR%": 15.38694,
          "Tracking Error": "8.6548",
          "Expense Ratio": "0.4",
          "Description": "iShares Global 100 ETF/AU is an exchange-traded fund incorporated in Australia. The Fund's objective seeks investment results that correspond to the performance of the S&P Global 100 Index.  The Index is designed to measure the performance of  large trans-national companies that are of major importance in the global markets."
        },
        {
          "Ticker": "IJR AU",
          "Name": "ISHARES S&P SMALL CAP ETF/AU",
          "Total Assets": 464.5715,
          "Price": 157.37,
          "1YR TR%": 10.33145,
          "3YR TR%": 15.81748,
          "Tracking Error": "12.0699",
          "Expense Ratio": "0.07",
          "Description": "iShares Core S&P Small-Cap ETF is an exchange-traded fund incorporated in Australia. The Fund seeks investment results that correspond to the performance of the S&P SmallCap 600 Index. The Fund uses a Representative sampling strategy to track the Index. The Index measures the performance of publicly traded securities in the small capitalization sector of the US equity market."
        },
        {
          "Ticker": "QUS AU",
          "Name": "BETASHARES S&P 500 EQ WT ETF",
          "Total Assets": 232.1317,
          "Price": 44.35,
          "1YR TR%": 12.78834,
          "3YR TR%": 16.01301,
          "Tracking Error": "9.50845",
          "Expense Ratio": "0.29",
          "Description": "BetaShares S&P 500 Equal Weight ETF is an exchange-traded fund that trades on the Australian Securities Exchange. The fund aims to provide an investment return that aims to track the performance of the S&P 500 Equal Weight Index, before taking into account fees and expenses."
        },
        {
          "Ticker": "IJH AU",
          "Name": "ISHARES S&P MID-CAP ETF/AUS",
          "Total Assets": 252.0138,
          "Price": 40.85,
          "1YR TR%": 15.53158,
          "3YR TR%": 16.03481,
          "Tracking Error": "11.3439",
          "Expense Ratio": "0.07",
          "Description": "iShares Core S&P Mid-Cap ETF is an exchange-traded fund incorporated in Australia. The ETF tracks the performance of the S&P MidCap 400 Index. The ETF holds mid-cap U.S. stocks. Its investments are chosen using a representative sampling strategy to track the Index. The ETF weights the holdings using a market capitalization  methodology and rebalances quarterly."
        },
        {
          "Ticker": "INIF AU",
          "Name": "INTELLIGENT INVESTOR AUS EQU",
          "Total Assets": 79.07571,
          "Price": 2.71,
          "1YR TR%": 5.950336,
          "3YR TR%": 16.06051,
          "Tracking Error": "#N/A N/A",
          "Expense Ratio": "0.97",
          "Description": "Intelligent Investor Australian Equity Income Fund is an exchange-traded fund incorporated in Australia. The Fund aims to achieve attractive risk-adjusted returns over the medium to long-term, while reducing the risk of permanent capital loss. The Fund primarily invests in the securities of companies listed on the ASX, but will also have some exposure to cash."
        },
        {
          "Ticker": "HJPN AU",
          "Name": "BETASHARES JAPAN ETF - CURRE",
          "Total Assets": 83.07215208,
          "Price": 16.57,
          "1YR TR%": 23.22653,
          "3YR TR%": 17.17581,
          "Tracking Error": "2.34156",
          "Expense Ratio": "0.56",
          "Description": "Betashares Japan ETF - Currency Hedged is an exchange traded fund incorporated in Australia. The Fund aims to provide an exposure to the equity securities that makeup the S&P Japan Exporters Hedged AUD Index, hedged for any change in the value of the JPY relative to the Australian Dollar."
        },
        {
          "Ticker": "MVB AU",
          "Name": "VANECK AUSTRALIAN BANKS ETF",
          "Total Assets": 177.6342,
          "Price": 29.11,
          "1YR TR%": 5.358097,
          "3YR TR%": 17.48136,
          "Tracking Error": "1.92239",
          "Expense Ratio": "0.28",
          "Description": "VanEck Vectors Australian Banks ETF is an exchange-traded fund incorporated in Australia. The Fund aims to provide investment returns (before fees and expenses) that closely track the returns of the MVIS Australia Banks Index."
        },
        {
          "Ticker": "NDIA AU",
          "Name": "GLOBAL X INDIA NIFTY 50 ETF",
          "Total Assets": 59.07475,
          "Price": 65.53,
          "1YR TR%": 13.38945,
          "3YR TR%": 18.08288,
          "Tracking Error": "9.14162",
          "Expense Ratio": "0.69",
          "Description": "Global X India Nifty 50 ETF is an exchange traded fund incorporated in Australia. The Fund aims to provide investors with a return that (before fees and expenses) tracks the performance of the NIFTY 50 Index by holding all of the shares that make up the index closely in proportion to their index weights."
        },
        {
          "Ticker": "MOAT AU",
          "Name": "VANECK MORNINGSTAR WIDE MOAT",
          "Total Assets": 665.1717261,
          "Price": 116.01,
          "1YR TR%": 22.75044,
          "3YR TR%": 18.32229,
          "Tracking Error": "11.9363",
          "Expense Ratio": "0.49",
          "Description": "VanEck Vectors Morningstar Wide Moat ETF is an exchange traded fund incorporated in Australia. The ETF aims to provide investment returns before fees and other costs which track the performance of the Morningstar Wide Moat Focus NR AUD Index. The ETF invests in a diversified portfolio of attractively priced companies with sustainable competitive advantages according to Morningstar's equity team."
        },
        {
          "Ticker": "FANG AU",
          "Name": "GLOBAL X FANG+ ETF",
          "Total Assets": 322.8391,
          "Price": 19.1,
          "1YR TR%": 49.21875,
          "3YR TR%": 19.80345,
          "Tracking Error": "17.7332",
          "Expense Ratio": "0.35",
          "Description": "Global X FANG+ ETF is an exchange traded fund incorporated in Australia. The Fund aims to provide investors with a return that (before fees and expenses) tracks the performance of the NYSE� FANG+� Index (the Index)."
        },
        {
          "Ticker": "VVLU AU",
          "Name": "VANGUARD GLB VAL EQT ACT ETF",
          "Total Assets": 561.0513,
          "Price": 66.2,
          "1YR TR%": 20.9426,
          "3YR TR%": 22.81624,
          "Tracking Error": "13.8014",
          "Expense Ratio": "0.28",
          "Description": "Vanguard Global Value Equity Active ETF is an exchange traded product incorporated in Australia. The Fund aims to provide long term capital appreciation through an active approach that invests in global equity securities demonstrating value characteristics."
        },
        {
          "Ticker": "ACDC AU",
          "Name": "GLOBAL X BATTERY TECH & LITH",
          "Total Assets": 624.7214435,
          "Price": 99.49,
          "1YR TR%": 21.97553,
          "3YR TR%": 23.02141,
          "Tracking Error": "6.31432",
          "Expense Ratio": "0.69",
          "Description": "Global X Battery Tech & Lithium ETF is an exchange traded fund incorporated in Australia. The Fund aims to provide investors with a return that (before fees and expenses) tracks the performance of the Solactive Battery Value-Chain Index."
        },
        {
          "Ticker": "FUEL AU",
          "Name": "BETA GLB ENERGY COM-CUR HEDG",
          "Total Assets": 205.1783,
          "Price": 6.42,
          "1YR TR%": 15.41784,
          "3YR TR%": 25.87205,
          "Tracking Error": "16.68",
          "Expense Ratio": "0.57",
          "Description": "Betashares Global Energy Companies ETF - Currency Hedged is an exchange-traded fund incorporated in Australia. The Fund aims to provide investment return that aims to track the performance of the Nasdaq Global ex-Australia Energy Companies Hedged AUD Index."
        }
       
];

export default data